/**
 * Centralized Content Configuration
 * =================================
 * 
 * This file serves as the single source of truth for content type ordering and configuration
 * across the entire application. All pages (home, articles index, individual articles) import
 * from this file to ensure consistency.
 * 
 * ## Purpose
 * - Define the canonical order of content types (decklist, article, report, spoiler, tutorial)
 * - Provide helper functions to query and combine collections in the correct order
 * - Centralize category labels and section titles
 * - Eliminate code duplication across pages
 * 
 * ## How to Change Content Order
 * To reorder content types throughout the entire application, simply modify the
 * CONTENT_TYPE_ORDER array below. All pages will automatically reflect the new order.
 * 
 * ## About the '#content' Import
 * The types imported from '#content' are AUTO-GENERATED by @nuxt/content based on the
 * schemas defined in content.config.ts. The '#content' path is a Nuxt virtual module
 * that doesn't exist as a physical file but is created at build time.
 * 
 * Collection naming pattern: {CollectionName}CollectionItem
 * - articles collection → ArticlesCollectionItem
 * - tutorials collection → TutorialsCollectionItem
 * - etc.
 * 
 * The TypeScript error "Cannot find module '#content'" is EXPECTED and HARMLESS.
 * These types are generated when Nuxt runs and will work correctly at runtime.
 * We suppress this error below with @ts-expect-error to keep the IDE clean.
 */

// @ts-expect-error - '#content' is a Nuxt virtual module with auto-generated types from content.config.ts
// These types are created at build time by @nuxt/content and are not available to static analysis
import type { ArticlesCollectionItem, TutorialsCollectionItem, DecklistsCollectionItem, ReportsCollectionItem, SpoilersCollectionItem } from '#content';

/**
 * Union type combining all article collection item types.
 * This allows functions to accept any content type while maintaining type safety.
 */
export type AnyArticle = 
    | ArticlesCollectionItem 
    | TutorialsCollectionItem 
    | DecklistsCollectionItem 
    | ReportsCollectionItem 
    | SpoilersCollectionItem;

/**
 * Valid category type identifiers.
 * These must match the collection names defined in content.config.ts
 */
export type CategoryType = 'decklist' | 'article' | 'report' | 'spoiler' | 'tutorial';

/**
 * The canonical order of content types throughout the application.
 * 
 * **To change the order site-wide, modify this array.**
 * All pages will automatically use the new order.
 * 
 * Current order: decklist → article → report → spoiler → tutorial
 */
export const CONTENT_TYPE_ORDER: readonly CategoryType[] = [
    'decklist',
    'article', 
    'report',
    'spoiler',
    'tutorial'
] as const;

/**
 * Category labels for display in Italian.
 * Used in the articles index page filter buttons.
 */
export const CATEGORY_LABELS: Record<CategoryType, string> = {
    decklist: 'Decklist',
    article: 'Articoli',
    report: 'Report',
    spoiler: 'Spoiler',
    tutorial: 'Tutorial'
} as const;

/**
 * Section titles for the home page.
 * Maps each category to its display title on the home page.
 */
export const HOME_SECTION_TITLES: Record<CategoryType, string> = {
    decklist: 'Top Decklists',
    article: 'Ultimi articoli',
    report: 'Resoconti dei tornei',
    spoiler: 'Spoilers & Set Reviews',
    tutorial: 'Tutorial'
} as const;

/**
 * Collection names as they appear in queryCollection() calls.
 * Maps category types to their actual collection names in content.config.ts
 */
export const COLLECTION_NAMES: Record<CategoryType, string> = {
    decklist: 'decklists',
    article: 'articles',
    report: 'reports',
    spoiler: 'spoilers',
    tutorial: 'tutorials'
} as const;

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Query all collections in the correct order defined by CONTENT_TYPE_ORDER.
 * 
 * @returns Promise resolving to an array of collection data arrays
 * 
 * @example
 * ```typescript
 * const collectionsData = await queryAllCollections();
 * // Returns: [decklistsData[], articlesData[], reportsData[], spoilersData[], tutorialsData[]]
 * ```
 */
export async function queryAllCollections() {
    const queries = CONTENT_TYPE_ORDER.map(type => 
        queryCollection(COLLECTION_NAMES[type] as any).all()
    );
    return await Promise.all(queries);
}

/**
 * Combine articles from multiple collections in the correct order.
 * 
 * @param collectionsData - Array of collection data arrays from queryAllCollections()
 * @returns Combined array of all articles maintaining the order
 * 
 * @example
 * ```typescript
 * const collectionsData = await queryAllCollections();
 * const allArticles = combineArticles(collectionsData);
 * ```
 */
export function combineArticles(collectionsData: any[][]): AnyArticle[] {
    if (collectionsData.length === 0) return [];
    
    // Start with the first collection and concat the rest in order
    return collectionsData.reduce((acc, data, index) => {
        if (index === 0) return data as AnyArticle[];
        return acc.concat(data as AnyArticle[]);
    }, [] as AnyArticle[]);
}

/**
 * Get home page sections in the correct order with their titles.
 * 
 * @returns Array of section configurations for the home page
 * 
 * @example
 * ```typescript
 * const sections = getHomeSections();
 * // Returns: [{ title: 'Top Decklists', category: 'decklist' }, ...]
 * ```
 */
export function getHomeSections() {
    return CONTENT_TYPE_ORDER.map(category => ({
        title: HOME_SECTION_TITLES[category],
        category
    }));
}

/**
 * Initialize an empty categories object with all category types.
 * Useful for grouping articles by category.
 * 
 * @returns Object with empty arrays for each category
 * 
 * @example
 * ```typescript
 * const categories = initializeCategories();
 * // Returns: { decklist: [], article: [], report: [], spoiler: [], tutorial: [] }
 * ```
 */
export function initializeCategories(): Record<CategoryType, AnyArticle[]> {
    return CONTENT_TYPE_ORDER.reduce((acc, category) => {
        acc[category] = [];
        return acc;
    }, {} as Record<CategoryType, AnyArticle[]>);
}

/**
 * Get collection names array in the correct order.
 * Useful for iterating through collections.
 * 
 * @returns Array of collection names
 * 
 * @example
 * ```typescript
 * const collections = getCollectionNames();
 * // Returns: ['decklists', 'articles', 'reports', 'spoilers', 'tutorials']
 * ```
 */
export function getCollectionNames(): string[] {
    return CONTENT_TYPE_ORDER.map(type => COLLECTION_NAMES[type]);
}
